version: '3.2'
services:
  rabbitmq:
      image: rabbitmq:3-management-alpine
      ports:
        - 5672:5672
        - 15672:15672
  configserver:
      image: spring-ms/configserver:1.0
      ports:
        - 8888:8888
      environment:
        - CONFIG_SERVICE_LOCATION=/usr/share/app/repo
      volumes:
        - ./config-repo:/usr/share/app/repo
      restart: always
  eurekaserver:
      image: spring-ms/eurekaserver:1.0
      ports:
        - 8761:8761
      environment:
        - CONFIG_SERVER=http://configserver:8888
        - EUREKA_SERVER=http://eurekaserver:8761/eureka/
      restart: always
  website:
      image: spring-ms/website:1.0
      ports:
        - 8001:8001
      environment:
        - CONFIG_SERVER=http://configserver:8888
        - EUREKA_SERVER=http://eurekaserver:8761/eureka/
      restart: always
  search-gateway:
      image: spring-ms/search-apigateway:1.0
      environment:
        - CONFIG_SERVER=http://configserver:8888
        - EUREKA_SERVER=http://eurekaserver:8761/eureka/
      restart: always
  fares-gateway:
      image: spring-ms/fares-apigateway:1.0
      environment:
        - CONFIG_SERVER=http://configserver:8888
        - EUREKA_SERVER=http://eurekaserver:8761/eureka/
      restart: always
  checkin-gateway:
      image: spring-ms/checkin-apigateway:1.0
      environment:
        - CONFIG_SERVER=http://configserver:8888
        - EUREKA_SERVER=http://eurekaserver:8761/eureka/
      restart: always
  book-gateway:
      image: spring-ms/book-apigateway:1.0
      environment:
        - CONFIG_SERVER=http://configserver:8888
        - EUREKA_SERVER=http://eurekaserver:8761/eureka/
      restart: always
  search:
      image: spring-ms/search:1.0
      environment:
        - CONFIG_SERVER=http://configserver:8888
        - EUREKA_SERVER=http://eurekaserver:8761/eureka/
      restart: always
  fares:
      image: spring-ms/fares:1.0
      environment:
        - CONFIG_SERVER=http://configserver:8888
        - EUREKA_SERVER=http://eurekaserver:8761/eureka/
      restart: always
  checkin:
      image: spring-ms/checkin:1.0
      environment:
        - CONFIG_SERVER=http://configserver:8888
        - EUREKA_SERVER=http://eurekaserver:8761/eureka/
      restart: always
  book:
      image: spring-ms/book:1.0
      environment:
        - CONFIG_SERVER=http://configserver:8888
        - EUREKA_SERVER=http://eurekaserver:8761/eureka/
      restart: always

